from BaseClasses import Location

class SonicManiaLocation(Location):
    game: str = "Sonic Mania"

#Bob-omb Battlefield

zone_clear_table = {
    "Green Hill (Act 1) Clear": 1,
    "Green Hill (Act 2) Clear": 2,
    "Chemical Plant (Act 1) Clear": 3,
    "Chemical Plant (Act 2) Clear": 4,
    "Studiopolis (Act 1) Clear": 5,
    "Studiopolis (Act 2) Clear": 6,
    "Flying Battery (Act 1) Clear": 7,
    "Flying Battery (Act 2) Clear": 8,
    "Press Garden (Act 1) Clear": 9,
    "Press Garden (Act 2) Clear": 10,
    "Stardust Speedway (Act 1) Clear": 11,
    "Stardust Speedway (Act 2) Clear": 12,
    "Hydrocity (Act 1) Clear": 13,
    "Hydrocity (Act 2) Clear": 14,
    "Mirage Saloon (Act 1 Normal) Clear": 15,
    "Mirage Saloon (Act 1 Knuckles) Clear": 16,
    "Mirage Saloon (Act 2) Clear": 17,
    "Oil Ocean (Act 1) Clear": 18,
    "Oil Ocean (Act 2) Clear": 19,
    "Lava Reef (Act 1) Clear": 20,
    "Lava Reef (Act 2) Clear": 21,
    "Metallic Madness (Act 1) Clear": 22,
    "Metallic Madness (Act 2) Clear": 23,
    "Titanic Monarch (Act 1) Clear": 24,
    "Titanic Monarch (Act 2) Clear": 25,

    "Special Stage 1 Clear": 26,
    "Special Stage 2 Clear": 27,
    "Special Stage 3 Clear": 28,
    "Special Stage 4 Clear": 29,
    "Special Stage 5 Clear": 30,
    "Special Stage 6 Clear": 31,
    "Special Stage 7 Clear": 32,
}
giant_ring_table = {
    "Green Hill (Act 1) Giant Ring - Knuckles Path": 80,
    "Green Hill (Act 1) Giant Ring - Lower Path Waterfall": 81,
    "Green Hill (Act 1) Giant Ring - Main Path": 82,
    "Green Hill (Act 2) Giant Ring - Near First Zipline Chain": 83,
    "Green Hill (Act 2) Giant Ring - Bottom Path Wall Behind Monitor": 84,
    "Green Hill (Act 2) Giant Ring - Waterfall Near Boss": 85,

    "Chemical Plant (Act 1) Giant Ring - Bottom Path Underwater Wall": 86,
    "Chemical Plant (Act 1) Giant Ring - Upper Path Near Yellow Springs": 87,
    "Chemical Plant (Act 1) Giant Ring - Upper Path After Large Ramp": 88,
    "Chemical Plant (Act 1) Giant Ring - Vertical Moving Blocks Bottom": 89,
    "Chemical Plant (Act 2) Giant Ring - Left After First Downwards Launch": 90,
    "Chemical Plant (Act 2) Giant Ring - Long Purple Pad Fake Wall": 91,
    "Chemical Plant (Act 2) Giant Ring - Upper Path Moving Blocks": 92,

    "Studiopolis (Act 1) Giant Ring - Backwards Ramp Near Start": 93,
    "Studiopolis (Act 1) Giant Ring - Top Path Fake Wall": 94,
    "Studiopolis (Act 1) Giant Ring - Lower Path Window Break Into Ramp": 95,
    "Studiopolis (Act 2) Giant Ring - Top Path Applause Sign": 96,
    "Studiopolis (Act 2) Giant Ring - Platforms After Wire Launch": 97,
    "Studiopolis (Act 2) Giant Ring - Top Path Badnik Bounce Chain": 98,

    "Flying Battery (Act 1) Giant Ring - 1": 99,
    "Flying Battery (Act 1) Giant Ring - 2": 100,
    "Flying Battery (Act 2) Giant Ring - 1": 101,
    "Flying Battery (Act 2) Giant Ring - 2": 102,
    "Flying Battery (Act 2) Giant Ring - 3": 103,
    "Flying Battery (Act 2) Giant Ring - 4": 104,

    "Press Garden (Act 1) Giant Ring - 1": 105,
    "Press Garden (Act 1) Giant Ring - 2": 106,
    "Press Garden (Act 2) Giant Ring - 1": 107,
    "Press Garden (Act 2) Giant Ring - 2": 108,
    "Press Garden (Act 2) Giant Ring - 3": 109,

    "Stardust Speedway (Act 1) Giant Ring - 1": 110,
    "Stardust Speedway (Act 1) Giant Ring - 2": 111,
    "Stardust Speedway (Act 1) Giant Ring - 3": 112,
    "Stardust Speedway (Act 2) Giant Ring - 1": 113,
    "Stardust Speedway (Act 2) Giant Ring - 2": 114,
    "Stardust Speedway (Act 2) Giant Ring - 3": 115,

    "Hydrocity (Act 1) Giant Ring - 1": 116,
    "Hydrocity (Act 1) Giant Ring - 2": 117,
    "Hydrocity (Act 1) Giant Ring - 3": 118,
    "Hydrocity (Act 2) Giant Ring - 1": 119,
    "Hydrocity (Act 2) Giant Ring - 2": 120,

    "Mirage Saloon (Act 1 Normal) Giant Ring - Inside Train Car": 121,
    "Mirage Saloon (Act 1 Knuckles) Giant Ring - 1": 122,
    "Mirage Saloon (Act 1 Knuckles) Giant Ring - 2": 123,
    "Mirage Saloon (Act 1 Knuckles) Giant Ring - 3": 124,
    "Mirage Saloon (Act 2) Giant Ring - 1": 125,
    "Mirage Saloon (Act 2) Giant Ring - 2": 126,
    "Mirage Saloon (Act 2) Giant Ring - 3": 127,

    "Oil Ocean (Act 1) Giant Ring - 1": 128,
    "Oil Ocean (Act 1) Giant Ring - 2": 129,
    "Oil Ocean (Act 1) Giant Ring - 3": 130,
    "Oil Ocean (Act 2) Giant Ring - 1": 131,
    "Oil Ocean (Act 2) Giant Ring - 2": 132,

    "Lava Reef (Act 1) Giant Ring - 1": 133,
    "Lava Reef (Act 1) Giant Ring - 2": 134,
    "Lava Reef (Act 2) Giant Ring - 1": 135,
    "Lava Reef (Act 2) Giant Ring - 2": 136,
    "Lava Reef (Act 2) Giant Ring - 3": 137,
    "Lava Reef (Act 2) Giant Ring - 4": 138,
    "Lava Reef (Act 2) Giant Ring - 5": 139,

    "Metallic Madness (Act 1) Giant Ring - 1": 140,
    "Metallic Madness (Act 1) Giant Ring - 2": 141,
    "Metallic Madness (Act 1) Giant Ring - 3": 142,
    "Metallic Madness (Act 2) Giant Ring - 1": 143,
    "Metallic Madness (Act 2) Giant Ring - 2": 144,

    "Titanic Monarch (Act 1) Giant Ring - 1": 145,
    "Titanic Monarch (Act 1) Giant Ring - 2": 146,
    "Titanic Monarch (Act 2) Giant Ring - 1": 147,


}
blue_sphere_table = {

"Blue Sphere (Set 1) - Orange/Brown Clear": 201,
"Blue Sphere (Set 1) - Aqua/Green Clear": 202,
"Blue Sphere (Set 1) - White/Orange Clear": 203,
"Blue Sphere (Set 1) - Lime/Green Clear": 204,
"Blue Sphere (Set 1) - Orange/Aqua Clear": 205,
"Blue Sphere (Set 1) - Purple/Tan Clear": 206,
"Blue Sphere (Set 1) - White/Lime Clear": 207,
"Blue Sphere (Set 1) - Gray/Light Gray Clear": 208,
"Blue Sphere (Set 2) - Magenta/Lime Clear": 209,
"Blue Sphere (Set 2) - Dark Blue/Aqua Clear": 210,
"Blue Sphere (Set 2) - Red/White Clear": 211,
"Blue Sphere (Set 2) - Purple/Orange Clear": 212,
"Blue Sphere (Set 2) - Light Blue/White Clear": 213,
"Blue Sphere (Set 2) - Blue/White Clear": 214,
"Blue Sphere (Set 2) - Blue/Orange Clear": 215,
"Blue Sphere (Set 2) - Blue/Off-White Clear": 216,
"Blue Sphere (Set 3) - Aqua/Light Blue Clear": 217,
"Blue Sphere (Set 3) - Yellow/Purple Clear": 218,
"Blue Sphere (Set 3) - Black/Dark Blue Clear": 219,
"Blue Sphere (Set 3) - Lime/Purple Clear": 220,
"Blue Sphere (Set 3) - Orange/Yellow (Dark Sky) Clear": 221,
"Blue Sphere (Set 3) - Pink/Aqua Clear": 222,
"Blue Sphere (Set 3) - Light Brown/Off-White Clear": 223,
"Blue Sphere (Set 3) - Brown/Off-White Clear": 224,
"Blue Sphere (Set 4) - Lime/White Clear": 225,
"Blue Sphere (Set 4) - Light Blue/Aqua Clear": 226,
"Blue Sphere (Set 4) - Orange/Yellow (Light Sky) Clear": 227,
"Blue Sphere (Set 4) - Purple/Off-White Clear": 228,
"Blue Sphere (Set 4) - Blue/Light Blue Clear": 229,
"Blue Sphere (Set 4) - Yellow/Dark Yellow Clear": 230,
"Blue Sphere (Set 4) - Blue/Green Clear": 231,
"Blue Sphere (Set 4) - Blue/Dark Blue Clear": 232,

"Blue Sphere (Set 1) - Orange/Brown Perfect": 241,
"Blue Sphere (Set 1) - Aqua/Green Perfect": 242,
"Blue Sphere (Set 1) - White/Orange Perfect": 243,
"Blue Sphere (Set 1) - Lime/Green Perfect": 244,
"Blue Sphere (Set 1) - Orange/Aqua Perfect": 245,
"Blue Sphere (Set 1) - Purple/Tan Perfect": 246,
"Blue Sphere (Set 1) - White/Lime Perfect": 247,
"Blue Sphere (Set 1) - Gray/Light Gray Perfect": 248,
"Blue Sphere (Set 2) - Magenta/Lime Perfect": 249,
"Blue Sphere (Set 2) - Dark Blue/Aqua Perfect": 240,
"Blue Sphere (Set 2) - Red/White Perfect": 241,
"Blue Sphere (Set 2) - Purple/Orange Perfect": 242,
"Blue Sphere (Set 2) - Light Blue/White Perfect": 243,
"Blue Sphere (Set 2) - Blue/White Perfect": 244,
"Blue Sphere (Set 2) - Blue/Orange Perfect": 245,
"Blue Sphere (Set 2) - Blue/Off-White Perfect": 246,
"Blue Sphere (Set 3) - Aqua/Light Blue Perfect": 247,
"Blue Sphere (Set 3) - Yellow/Purple Perfect": 248,
"Blue Sphere (Set 3) - Black/Dark Blue Perfect": 249,
"Blue Sphere (Set 3) - Lime/Purple Perfect": 240,
"Blue Sphere (Set 3) - Orange/Yellow (Dark Sky) Perfect": 241,
"Blue Sphere (Set 3) - Pink/Aqua Perfect": 242,
"Blue Sphere (Set 3) - Light Brown/Off-White Perfect": 243,
"Blue Sphere (Set 3) - Brown/Off-White Perfect": 244,
"Blue Sphere (Set 4) - Lime/White Perfect": 245,
"Blue Sphere (Set 4) - Light Blue/Aqua Perfect": 246,
"Blue Sphere (Set 4) - Orange/Yellow (Light Sky) Perfect": 247,
"Blue Sphere (Set 4) - Purple/Off-White Perfect": 248,
"Blue Sphere (Set 4) - Blue/Light Blue Perfect": 249,
"Blue Sphere (Set 4) - Yellow/Dark Yellow Perfect": 240,
"Blue Sphere (Set 4) - Blue/Green Perfect": 241,
"Blue Sphere (Set 4) - Blue/Dark Blue Perfect": 242,


}

achievement_table = {
    "Achievement: Superstar": 160,
    "Achievement: That's a Two-fer": 161,
    "Achievement: Magnificent Seven": 162,
    "Achievement: See You Next Game": 163,
    "Achievement: Full Medal Jacket": 164,
    "Achievement: No Way? No Way!": 165,
    "Achievement: Now It Can't Hurt You Anymore": 166,
    "Achievement: Triple Trouble": 167,
    "Achievement: The Most Famous Hedgehog in the World": 168,
    "Achievement: Window Shopping": 169,
    "Achievement: Crate Expectations": 170,
    "Achievement: King of Speed": 171,
    "Achievement: Boat Enthusiast": 172,
    "Achievement: The Password is 'Special Stage'": 173,
    "Achievement: Secret Sub": 174,
    "Achievement: Without a Trace": 175,
    "Achievement: Collect 'Em All": 176,
    "Achievement: Professional Hedgehog": 177,
}

location_table = {**zone_clear_table,**giant_ring_table,**blue_sphere_table, **achievement_table}
